version: "3.6"

services:
  # miner instance
  miner:
    container_name: miner
    image: balenalib/raspberrypi4-64-debian-node:latest-buster-build
    build:
      context: ./miner
      dockerfile: Dockerfile
    networks:
      - default-network
#    ports:
#      - "8080:8080"
#      - "8081:8080"
#      - "8080:8081"
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyS0"

#volumes:
#  dbdatapg:
#  dbdatapg2:

networks:
  default-network:
    driver: bridge
